### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by romgrk**
Found 2 leaks via valgrind, there are possibly more.

### CODE REVIEW

**Comment by romgrk** [comment]
Problem with:
```js
const regex = new GLib.Regex('[A-Z][a-z]+', 0, 0)

const [success, match] = regex.match('Hello World', 0)
const matches = []
while (match.matches()) {
  const word = match.fetch(0)
  matches.push(word)
  match.next(null)
}
match.free()
regex.unref()
```

`'Hello World'` is currently leaked I think. However, freeing it right after the `g_regex_match` call will yield invalid results in `match.matches()`. We need to find when to free that string.

**Comment by romgrk** [comment]
So from discussions on IRC gnome#introspection, I gather that API:s that require non-transfer_everything strings with a lifetime longer than the current function call should be considered non-introspectable. `g_regex_match` is one of those cases, so we'll need to replace that test with something else.

I will therefore re-implement the cleanup of utf8/filename values in `FreeGIArgument`.

**Comment by wotzlaff** [comment]
Great news. Thanks for investigating. GIR is quite undocumented at some points...

**Comment by romgrk** [comment]
Yes, gnome developpers are lacking in some aspects, mainly community-building and documentation. Which means that basically the whole ecosystem in only fully usable to the main developpers, it's a PITA to just take one lib and use it. So yeah if you have more advanced questions, the best place to ask for is [IRC](https://wiki.gnome.org/Community/GettingInTouch/IRC) -_-

**Comment by wotzlaff** [comment]
Could you explain briefly how did you find out about the memory leaks. Valgrind gives me to much output. At least I do not have an idea that the problem comes from the string in the test you mentioned above.

**Comment by romgrk** [comment]
Sure, so yes valgrind does produce a lot of output, but there is no way around digging into it. I focused in what seemed to be the major leaks, which were in the two stacks illustrated below. The first one shows the leaked objects being initialized inside `V8ToGIArgument` and inside `g_strdup`. There was only one place where `g_strdup` was used in `V8ToGIArgument` so that answers the question.

For the second one on the bottom there is a symbol missing (`???`) but it's in `GetConstantValue` which is about 10 lines, so it wasn't very hard finding where the leak was.

Screenshot from 2020-06-26 03-07-43

For this first pass I ignored any stack that didn't include any of node-gtk functions. For example, some stacks are only pure V8 functions, and the functions seem related to it's own internal heap management, which is possibly complex enough to confuse valgrind, notably due to [pointer tagging and pointer compression](https://v8.dev/blog/pointer-compression) which means that V8 pointers must be transformed otherwise they don't point the correct location. TBH I don't know how valgrind works, but my general understanding is that they provide a custom shim for malloc/free, then inspect the heap & stack to check for references to allocated memory.

Also for I've heard (probably on IRC or some forum, don't remember where) that GIR/GObject "leaks" some base objects but that it's kind of okay. Not 100% sure what was meant by that, maybe some objects whose lifetime needs to be as long as the application. Anyway, those "leaks" are of this type:

```
16 bytes in 1 blocks are possibly lost in loss record 2,845 of 14,326
   at 0x483977F: malloc (vg_replace_malloc.c:307)
   by 0x8F490E9: g_malloc (in /usr/lib/libglib-2.0.so.0.6400.3)
   by 0x8F6A7EF: g_slice_alloc (in /usr/lib/libglib-2.0.so.0.6400.3)
   by 0x8EB39E6: ??? (in /usr/lib/libgobject-2.0.so.0.6400.3)
   by 0x8EC7ABD: ??? (in /usr/lib/libgobject-2.0.so.0.6400.3)
   by 0x8EC7E9E: ??? (in /usr/lib/libgobject-2.0.so.0.6400.3)
   by 0x8ED3288: ??? (in /usr/lib/libgobject-2.0.so.0.6400.3)
   by 0x8ED6301: g_type_add_interface_static (in /usr/lib/libgobject-2.0.so.0.6400.3)
   by 0xBF78FE6: gtk_action_get_type_once (gtkaction.c:176)
   by 0xBF79B14: gtk_action_get_type (gtkaction.c:176)
   by 0x485F361: g_registered_type_info_get_g_type (in /usr/lib/libgirepository-1.0.so.1.0.0)
   by 0x8E0C3DB: GNodeJS::MakeClass(_GIBaseInfoStub*) (gobject.cc:480)
```

Because we see it's inside `g_registered_type_info_get_g_type` which returns a `GType` (aka `unsigned long`), we know that there is nothing we can do about that because it's not memory to which we are provided a reference. 

That's all I can share for now, this was my first serious use of valgrind, so you can probably find better tutorials online ^^

**Comment by wotzlaff** [comment]
Thanks. That's already quite helpful.

**Comment by romgrk** [comment]
Weird test failure for node 14 in tests/boxed__initialization.js. Seems to be on master as well, and was introduced some time ago. Also travis results don't show anymore in GH -_-

**Pull request merged**
