### PR TITLE
Fix tests and install.sh for Ubuntu 20 action runner.

### PR DESCRIPTION
**Pull request by chfritz**
I broke the tests in https://github.com/romgrk/node-gtk/commit/0fba37c2c0c005f20aef5d0e9d3b6d52ee90cfa2, this fixes them again.

Undoing some of the changes from https://github.com/romgrk/node-gtk/commit/d93cba660b76ba221e765254647a5e8d632c56c4 now that we've switched the action runner back to Ubuntu 20.

### CODE REVIEW

**Comment by romgrk** [comment]
Ah, right, soup version changed. That's terrible. I've been meaning to switch the test suite to libgimarshallingtest which is meant to avoid this kind of situation, but not enough time.

**Comment by chfritz** [comment]
I've spend all morning today trying to fix the tests, but haven't been able to. Even though on my Ubuntu 20 machine with node 16 the tests all pass, on CI the `callback` test always failed. Similarly the `object__initialization` test failed on Windows. I've disabled them for now, so that you can publish new binaries based on Ubuntu 20 (the one that were produced for node-gtk 0.13 were still created on Ubuntu 22, i.e., won't work on Ubuntu 20).

**Comment by romgrk** [comment]
Sounds good, I'm happy publishing the binaries without that test.

At some point I'll probably revert those changes though to migrate to ubuntu 22.

**Comment by romgrk** [comment]
Published v0.14 and started the workflow.

Thanks to past me for leaving me a [release checklist](https://github.com/romgrk/node-gtk/blob/master/doc/contributing.md#release-checklist), I'd be lost without his notes.

**Pull request merged**
