### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by ten0s**
* Upgraded node-gyp
* Upgraded Ubuntu to 22.04
* Ported tests to Soup3
* Fixed GST tests on MacOS

### CODE REVIEW

**Comment by ten0s** [comment]
Fixes #326

**Comment by romgrk** [comment]
Do you wanna debug the error test? Otherwise I'm fine if we just skip it on windows, I don't have much resources to invest in this project but I'd rather have it working with inaccuracies than not working at all. We can open an issue to track the bug.

**Comment by ten0s** [comment]
I disabled a couple of tests on Mac and Windows. Windows passed. 
Mac sometimes fails during setup phase. 
See https://github.com/ten0s/node-gtk/actions/runs/5297965131/jobs/9590225913

**Comment by romgrk** [comment]
Alright, so this can be merged? The changes LGTM.

Any idea why macOS is flaky?

**Comment by ten0s** [comment]
It can be merged. 

Regarding Mac, similar issue was in Homebrew half year ago, was fixed after a while

**Comment by romgrk** [comment]
Got it. Thanks for the PR!

**Pull request merged**
