### PR TITLE
Clean up GStreamer example

### PR DESCRIPTION
**Pull request by sdroege**
- Don't require GTK but use a plain GLib main loop
- Add a bus watch to handle errors, end of stream, etc.
- Handle errors from setting the pipeline to PLAYING
- Remove dysfunctional setInterval() code that prevented the application
  from exiting cleanly when the main loop is finished
- Remove 'child-added' signal handler, which is not really
  representative of GStreamer applications
- Set videotestsrc 'num-buffers' property to 100 to cleanly end the
  stream after 100 frames

### CODE REVIEW

**Comment by wotzlaff** [comment]
Thanks for that update. Now the example really looks GStreamer-like.
The old example came from a time when nothing was really working. So I am very happy that you took some time to provide an update.

**Comment by romgrk** [comment]
LGTM :) Minor lint before I merge, could you use remove `var` and use `const`/`let`? Newly written code shouldn't mix both styles

**Comment by sdroege** [comment]
Thanks, updated accordingly. Better like this :)

Personally I prefer putting `;` at the end of statements but you don't do that anywhere else so I left it without.

**Comment by romgrk** [comment]
IMHO `;` adds unnecessary noise to the source code, but it's indeed a controversial opinion that I have :laughing:  But yes consistency is usually preferable to preferences. Thanks for the cleanup!

**Pull request merged**
