### PR TITLE
Test callback functionality

### PR DESCRIPTION
**Pull request by wotzlaff**
I added tests related to issue #187 and pulls #194 & #195.
Hopefully this is enough to show what was broken.

### CODE REVIEW

**Comment by romgrk** [comment]
Looks great :) waiting for the tests to complete and will merge.

**Comment by romgrk** [comment]
Tests failed :/
```
  1) callback__threading.js:
     Failed: callback should be called from another thread
TypeError: task.runInThread is not a function
    at /home/travis/build/romgrk/node-gtk/tests/callback__threading.js:14:10
    at new Promise (<anonymous>)
    at /home/travis/build/romgrk/node-gtk/tests/callback__threading.js:9:9
    at Object.describe (/home/travis/build/romgrk/node-gtk/tests/__common__.js:56:5)
    at Object.<anonymous> (/home/travis/build/romgrk/node-gtk/tests/callback__threading.js:8:8)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by wotzlaff** [comment]
Great. I have no idea where this problem comes from. The function `runInThread` should be available since GLib 2.36. Maybe this is an issue with introspection. I will try to find out what's wrong.
On my system the test is successfully running.

**Comment by wotzlaff** [comment]
Too bad that the `runInThread` method of `GTask` didn't work. That would have been a quite simple test. I still have no idea to fix this.
So I propose another test which seems to be working.

**Comment by wotzlaff** [comment]
Ok, another macOS glitch here. Now I'm totally lost. Maybe I'm just taking back the threading test.

**Comment by romgrk** [comment]
About the current test, wouldn't `g_timeout_add` be more appropriate than an idle callback? Also if you're gonna use an idle callback, why not set `G_PRIORITY_HIGH_IDLE`? Can't hurt.

Otherwise, which tests are best to test the callback functionnality? If really we can't make it work on macOS, as a last resort you can skip thoses tests on macOS: `if (process.platform === 'darwin') common.skip()`.

**Comment by wotzlaff** [comment]
I agree that using `g_timeout_add` is more appropriate. So the first test does what it's created to do.

About the second test: I could not find a reliable way to spawn a thread from GLib. Maybe it's best to remove the test as threading should be avoided in GLib anyway. I just wanted to be sure that callbacks are also running if they are started not from the main thread.
Here a summary of the problems:
- On bionic the method `runInThread` of `GTask` is not available. I can confirm that it works on focal. Maybe there's a change in GIR annotation between the version of GLib.
- On macOS the `create-offer` signal of `GstWebRTCBin` is not processed. This is probably due to some missing dependency. I can try to find out what's wrong there.

**Comment by romgrk** [comment]
I like your Gst tests because until know they've covered areas of the code that I never had to test because I don't have use-cases for them. So if you want you could re-add the Gst test and investigate the bug, or skip it on macOS, as I've described above. (I'd want that test :P)
Btw when investigating missing dependencies, the best method is to try to build an equivalent C program and check what libs it needs to compile.

And about threading, my understanding is that JS in strictly single threaded, so even when you `.runInThread(...)`, what is really happening is that glib will initiate the function call in another thread, then it will it the code that you've added for out-of-main-thread callbacks, which will run its magic and call the JS function from the main thread. So I mean we can add it for a completeness purpose, but it's not going to make multi-threading possible in JS.

**Comment by romgrk** [comment]
As for the `.runInThread`, you can also add a conditional test, that runs only if the method is present. We can test on our own machines, and once focal is available on travis we can update our setup to use it. So you could re-add that test, and create an issue to track things to do when `focal` arrives on travis.

**Comment by romgrk** [comment]
One more thing, as I've said in another PR, it would be good to centralize a bit more some tests, eg this one could be `callback.js` for all callback things. Reason is that each test file needs to re-load the whole GIRepository information, so each file adds a few hundred milliseconds to our tests, and if tests are too long to run we run them less often.

**Comment by wotzlaff** [comment]
You're right about the threading: The aim of my code was to run the callbacks in the main thread. So calling `runInThread` might give a wrong impression. This seems the only possibility to spawn a thread in GLib anyway.

I tried to follow your comments in my recent commits. Hopefully the tests are now running. At least I found an issue for the macOS glitch. Maybe it is solved now. But probably it'll show now what's wrong.

**Comment by wotzlaff** [comment]
The tests are passing now:
- The macOS issue is gone.
- I do not really like checking for the existence `runInThread` because if it's not available the testing code is not running. Now since the GStreamer test is also running, this seems fine to me. But maybe you see a better solution.

**Comment by romgrk** [comment]
Looks fine to me, we can remove the `runInThread` check when the dependencies are more up to date (glib >= 2.36).

**Pull request merged**
