### PR TITLE
Fix handling of GQuarks in Error test

### PR DESCRIPTION
**Pull request by wotzlaff**
According to https://github.com/romgrk/node-gtk/pull/225#discussion_r513235539 `GQuark`s should be registered. I did not respect this rule in the original test.

### CODE REVIEW

**Comment by romgrk** [comment]
Cool! While you're there I forgot to ask but could you assign `common.xxxx` functions to a variable and use those? It will be more readable that way.

**Comment by wotzlaff** [comment]
Yep. I should not have used an old test as template.
Maybe we should define some best practices for writing tests (in form of reference to some particular test file) somewhere.

**Comment by romgrk** [comment]
Oh one more thing sorry :/ Could you use `common.expect(v1, v2)` instead of `assert` when you compare 2 values? It's better because it will print both values if it fails, and that shows up in the logs. `assert` doesn't leave enough information to debug a failing travis build.

And yes, I should write a template. In general, the newer the file, the better it is structured.

**Comment by wotzlaff** [comment]
Better structure is always good. I followed your leads and hope that I can remember to start from there next time I write a test (until we got a template).

**Pull request merged**
