### PR TITLE
types initial contrib

### PR DESCRIPTION
**Pull request by cancerberoSgx**
* npm run generate-types-test should generate a couple of tmp.* files
 * I think I'm done for today - as said I tried to include the private/protected part in the typings - perhaps you want to remove it - if not we need to finish it
 * the generated types are far from finish - but I think we can start discusion
 * I have a couple of tricks to deal with the generation - typescript is my strong part - and not so much C++/gobject based libraries so we can complement
 * just tell me which parts do you want to tacke with typescript and I can help you - from my side feel free to play with this remove as you feel... TypeScript reall worth it particularly for libraries - and for these monsters it will be awesome (for me at least that mostly know JS  and very little about the APIs....
 * probably you can fix some warnings and review the inspect.ts - (I forgot to rename it)
 just tell me how to proceed so we don't work twice. THanks!!!

### CODE REVIEW

**Comment by cancerberoSgx** [comment]
script is currently broken - fixing it now - but I kind of quit for today - and github won't let me upload the file for some reason so this is it just in case you are courious - will update here when fixed https://drive.google.com/open?id=1Y9V6vwS8vv2Sh7jHW0bClGSx2ldQa9vl

**Comment by donnisnoni95** [comment]
what about the version when user try this... for example `require('Gtk', '2,0')`

**Comment by cancerberoSgx** [comment]
> what about the version when user try this... for example `require('Gtk', '2,0')`

Yes, I think There's a TODO about that  - Is doable (auto-cast to Gtk) and the versions too but we should also consider require('NewThing') - in which case compilation will fail unless users hard cast. An easy / safe alternative would be users casting manually `require('Gtk', '2,0') as Gtk2`. Taking notes thanks

**Comment by JumpLink** [comment]
There is now initial support for node-gtk in [ts-for-gjs](https://github.com/sammydre/ts-for-gjs) (including examples), maybe this is interesting for this pr.

**Comment by romgrk** [comment]
Closing for inactivity but re-open if you want. ts-for-gjs does seem to produce interesting results.

**Pull request closed without merging**
