### PR TITLE
build: node 18

### PR DESCRIPTION
**Pull request by romgrk**
Adapt for node 18 & 20 changes.

### CODE REVIEW

**Comment by romgrk** [comment]
@ten0s Do you remember why that line was necessary? It seems to break vfuncs out arguments:

https://github.com/romgrk/node-gtk/blob/79b6ef4469b6eea770e273574193d40a54bce5a5/src/value.cc#L880

**Comment by ten0s** [comment]
@romgrk, it was needed for V8ToGIArgument to make it work on Windows, maybe it's not needed for V8To**Out**GIArgument, I never faced such an issue.

**Comment by ten0s** [comment]
BTW, I created https://github.com/romgrk/node-gtk/pull/336 some time ago, not sure why it got closed.

I also update actions and readme, take a look at https://github.com/ten0s/node-gtk

**Comment by romgrk** [comment]
Neat, didn't saw, haven't been around much. Do you wanna re-open that PR? Is it ready to be merged?

**Comment by ten0s** [comment]
error.js failed on Windows. Not sure why. It worked back then

**Pull request closed without merging**
