### PR TITLE
fix: use size from g_constant_info_get_value (closes #234)

### LINKED ISSUE #234: Handle console warnings for invalid constant size
```
[WARN] gi.cc: GetConstantValue: 136: Couldn't load HarfBuzz.LANGUAGE_INVALID: invalid constant size: 0
```

We should either handle the case, or decide that it's acceptable that some constants have size 0. I'm not sure what that means though.

### PR DESCRIPTION
**Pull request by romgrk**

### CODE REVIEW

**Comment by wotzlaff** [comment]
We run into problem if we do this:
```node
const gi = require('.')
const hb = gi.require('HarfBuzz')
```
exits with
```
FATAL ERROR: v8::Object::SetAlignedPointerInInternalField() Unaligned pointer
 1: 0xa17c40 node::Abort() [node]
 2: 0xa1804c node::OnFatalError(char const*, char const*) [node]
 3: 0xb9584a v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0x7f1a240519c3  [/home/nico/projects/node-gtk/lib/binding/node-v72-linux-x64/node_gtk.node]
 5: 0x7f1a2405167c  [/home/nico/projects/node-gtk/lib/binding/node-v72-linux-x64/node_gtk.node]
 6: 0xc02cab  [node]
 7: 0xc03b9d v8::internal::Builtins::InvokeApiFunction(v8::internal::Isolate*, bool, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*, v8::internal::Handle<v8::internal::HeapObject>) [node]
 8: 0xce7f26  [node]
 9: 0xce852a v8::internal::Execution::New(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [node]
10: 0xba72f0 v8::Function::NewInstanceWithSideEffectType(v8::Local<v8::Context>, int, v8::Local<v8::Value>*, v8::SideEffectType) const [node]
11: 0xba75ac v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const [node]
12: 0x7f1a24052b74 GNodeJS::WrapperFromBoxed(_GIBaseInfoStub*, void*, bool) [/home/nico/projects/node-gtk/lib/binding/node-v72-linux-x64/node_gtk.node]
13: 0x7f1a2406161f GNodeJS::GIArgumentToV8(_GIBaseInfoStub*, _GIArgument*, long, bool) [/home/nico/projects/node-gtk/lib/binding/node-v72-linux-x64/node_gtk.node]
14: 0x7f1a240582f8 GetConstantValue(Nan::FunctionCallbackInfo<v8::Value> const&) [/home/nico/projects/node-gtk/lib/binding/node-v72-linux-x64/node_gtk.node]
15: 0x7f1a2405891c  [/home/nico/projects/node-gtk/lib/binding/node-v72-linux-x64/node_gtk.node]
16: 0xc019e9  [node]
17: 0xc037d7 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
18: 0x1409319  [node]
Aborted (core dumped)
```

(Just to mention it. I haven't thought about this problem, yet.)

**Comment by romgrk** [comment]
All good, the tests caught it ^^
I'll do more research on what to do with this thing.

**Comment by romgrk** [comment]
I've spoken with the devs about this case ad have applied their suggestion. I've left a comment to give more context about what is happening. If you want to review before I merge go ahead.

**Comment by wotzlaff** [comment]
It seems that HarfBuzz is still failing with `Unaligned pointer`. This also happens for Travis on Ubuntu.
Any idea how to handle this?

**Comment by romgrk** [comment]
It works on my machine, but I have an idea why it might be aborting:

Screenshot from 2020-11-03 02-46-41
Screenshot from 2020-11-03 02-46-57

Maybe considering `0` as an `hb_language_t` struct isn't a good idea. PyGObject seems to return `None` for that value, I'll return `null`, that's probably the best we can do.

**Comment by romgrk** [comment]
Done.

**Comment by wotzlaff** [comment]
It seems to work now. I have nothing to add.

**Comment by romgrk** [comment]
:+1:

**Pull request merged**
