### PR TITLE
add node-gtk logo

### PR DESCRIPTION
**Pull request by donnisnoni95**
It's good to get a new logo for node-gtk

### CODE REVIEW

**Comment by donnisnoni95** [comment]
Ahhh... forgot to pass Travis...  😅

**Comment by romgrk** [comment]
Cool, thanks!

**Comment by romgrk** [comment]
It's not being displayed properly in the readme :/

Screenshot from 2019-09-29 15-50-09

**Comment by donnisnoni95** [comment]
fixed by #147  💯

**Pull request merged**
