### PR TITLE
Fix function call with struct output

### PR DESCRIPTION
**Pull request by wotzlaff**
Here's the test for #189.
Maybe it needs some more dependencies to run Travis...

Probably it'll be better to find a test with a more basic function. But I don't know where to find such a function.

### CODE REVIEW

**Comment by romgrk** [comment]
Ok, and can you include the fix with the test? If committed as such on master the master branch would not pass tests. The goal is that master is buildable & usable at any commit.

**Comment by wotzlaff** [comment]
I should have added the fix, sorry.

**Comment by romgrk** [comment]
From the tests on linux:
```
Error: Typelib file for namespace 'GstSdp' (any version) not found
    at Object.giRequire [as require] (/home/travis/build/romgrk/node-gtk/lib/index.js:504:27)
    at Object.<anonymous> (/home/travis/build/romgrk/node-gtk/tests/function_call__out_struct.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

You'll need to install the package for that.

**Comment by wotzlaff** [comment]
I changed the test to use some GLib functions. Should work now.

**Comment by romgrk** [comment]
LGTM, though memory management shouldn't be needed in JS, even when `transfer = EVERYTHING`. I wonder what those `.free()` and `.unref()` really do, it might cause a segfault I think. I'll investigate in a separate issue.

**Pull request merged**
